### ISSUE TITLE
Issue with main Light

### ISSUE THREAD

**Issue by grigarth** [alaltitov/display#1]
Hello Alexey,

Thank you for this excellent code. 

I have an issue with Main Light (also with brightness and temperature) and Night light. 
The Accent light works fine with relay. 
When I change the states in home assistant I see the correct reflect on the screen. But the screen itself does nothing when I push on it. 
Could it be a specific issue with my HA (up to date)? 
Attached the log file 
[logs_display_logs.txt](https://github.com/user-attachments/files/18136346/logs_display_logs.txt)
Thank you in advance
Best regards

**Comment by alaltitov** [comment]
@grigarth Hello! It's quite hard to say without having the device that you have. What kind of devices do you have "main light" and "night light"? Is this some kind of integration? In any case, even if we don't take into account brightness and kelvins, night light should work on the switch principle. In my code, when you click the button, the "light.toggle" service is simply launched. And if it works properly and nothing blocks it, everything should be fine.
Try looking in Home Assistant in Developer tools on the "Actions" tab at the work of the light.toggle service. Does it work correctly with your lamps (entities)?
In principle, there is nothing special about the "night light" button, it simply launches the light.toggle service with a specific entity:
`            # NIGHT LIGHT
            - button:
                ...
                widgets:
                  - button:
                      id: light_night_btn
                      ...
                      **_on_press:
                        - homeassistant.service:
                            service: light.toggle
                            data:
                              entity_id: light.lumi_v3_48df_light_**
                  - label:
                      id: light_night
                      ...`

**Comment by grigarth** [comment]
Alexey

Thank you very much for your answer,
You helped me a lot. The problem was that I didn't knew that there are entity_id in the lvgl.yaml to be changed too (those are probably yours)).
Everything works just great now
The device is ESP32-S3 N16R8 480x480
Now I have to buy other equipments to populate other shirtcuts))) or to find out how to disable them.
Thank you again and have a nice evening
Best regards

**Comment by alaltitov** [comment]
Solved

**Comment by tapd** [comment]
Firstly, THANK YOU so much for taking the initiative and starting this project!!!!

Sorry for commenting on a closed post, but I am having the exact same issue even after updating lvgl.yaml with the correct entities. I then decided to change the homeassistant.service: and service: sections to e homeassistant.action: and action: respectively to see if that made any difference, but no success.

I realise it's not doing anything too complex, just a light.toggle, but would you have any suggestions of what I may have missed?

Thank you

**Comment by alaltitov** [comment]
Good day! Show your lvgl.yaml file in full and specifically the piece of code that is causing the problems.

**Comment by tapd** [comment]
Hello, the lvgl.yaml is unchanged except for the entities, here's the part for one of the buttons below, let me know if you want me to post the entire file as the only changes are the entities. Thank you

            - button:
                bg_opa: TRANSP
                border_opa: TRANSP
                shadow_opa: TRANSP
                pad_all: 0
                grid_cell_column_pos: 0
                grid_cell_row_pos: 1
                grid_cell_x_align: STRETCH
                grid_cell_y_align: STRETCH
                grid_cell_column_span: 1
                grid_cell_row_span: 1
                widgets:
                  - label:
                      id: light_main_label
                      align: TOP_MID
                      text_font: nunito_18
                      text_color: color_dark_gray
                      text: "Main light"
                  - button:
                      id: light_main_btn
                      width: 90
                      height: 90
                      y: 20
                      align: CENTER
                      bg_opa: TRANSP
                      shadow_opa: TRANSP
                      border_color: color_dark_gray
                      border_width: 2
                      radius: 50
                      on_press:
                        - homeassistant.service:
                            service: light.toggle
                            data:
                              entity_id: light.dining_lamp
                      widgets:
                        - label:
                            id: light_main
                            align: CENTER
                            text_font: icons_72
                            text_color: color_dark_gray
                            text: "${lights}"

**Comment by tapd** [comment]
Yes the button is displayed but remains grey when pushed and no logs appear in HA. But if I control the light from HA, the button on the screen lights up. It's quite odd as it seems to be communicating with HA only in one direction. And a light.toggle from DevTools controls the light as expected. I feel like I've missed something very simple that's preventing this from working.

**Comment by Shuraxxx** [comment]
Same problem

**Comment by alaltitov** [comment]
@tapd @Shuraxxx I just tried it and I have the same thing. In another project I have the same thing and it happens because Home Assistant is on my virtual machine on a Mac, and when the Mac goes to sleep, such problems begin! The solution is to simply restart the home assistant from the frontend! In my case, it always works. Whether these are features of the light bulb or something else, I have not yet figured out. But every time the server with HA goes to sleep, this thing happens! It turns out that you need to restart the home assistant, but perhaps your problem is different and you need to take the original file and change the entities one by one, checking the devices and checking if there are extra spaces or symbols in another language

**Comment by tapd** [comment]
@alaltitov My HA server is also on a VM in Proxmox but it's powered 24/7 as a lot of things in the house runs on HA. In saying that I had restarted HA numerous times while testing both from the frontend as well as the whole VM in Proxmox. I did that just in case the yaml files weren't being parsed properly after being modified, but made no difference. So I feel the issue is elsewhere. As I mentioned in my original post, I had also changed change the homeassistant.service: and service: sections to homeassistant.action: and action: respectively which also made no difference. I will have a go at your suggestion of changing the entities one by one tomorrow and let you know if that makes a difference. Thank you.

**Comment by alaltitov** [comment]
@Shuraxxx  You have my entities in your firmware. Naturally, nothing will work with my entities. Wherever entity_id is specified, you need to replace it with your own. For example, for Main Light(entity_id: light.cbe_rgbcw_wi_fi_bluetooth_light):
```          
           - button:
                bg_opa: TRANSP
                border_opa: TRANSP
                shadow_opa: TRANSP
                pad_all: 0
                grid_cell_column_pos: 0
                grid_cell_row_pos: 1
                grid_cell_x_align: STRETCH
                grid_cell_y_align: STRETCH
                grid_cell_column_span: 1
                grid_cell_row_span: 1
                widgets:
                  - label:
                      id: light_main_label
                      align: TOP_MID
                      text_font: nunito_18
                      text_color: color_dark_gray
                      text: "Main light"
                  - button:
                      id: light_main_btn
                      width: 90
                      height: 90
                      y: 20
                      align: CENTER
                      bg_opa: TRANSP
                      shadow_opa: TRANSP
                      border_color: color_dark_gray
                      border_width: 2
                      radius: 50
                      on_press:
                        - homeassistant.service:
                            service: light.toggle
                            data:
                              entity_id: light.cbe_rgbcw_wi_fi_bluetooth_light      
                              # Change the entity from your Home Assistant
                      widgets:
                        - label:
                            id: light_main
                            align: CENTER
                            text_font: icons_72
                            text_color: color_dark_gray
                            text: "${lights}"
```
This needs to be replaced everywhere.
